import { NextRequest, NextResponse } from "next/server";
import { readStoredMedia } from "@/lib/storage/blob";

export const runtime = "nodejs";

/**
 * Serves files stored via Netlify Blobs, which has no public CDN URL of its own.
 * Everything served here (logos, QR PDFs/PNGs) is meant to be publicly viewable —
 * the same access level Vercel Blob's `access: "public"` mode provided — so this
 * route intentionally does not require authentication. It only reads existing
 * keys already generated by the app (lib/storage/blob.ts); it never lists or
 * accepts arbitrary keys beyond what's in the URL path.
 */
export async function GET(_request: NextRequest, { params }: { params: Promise<{ key: string[] }> }) {
  const { key } = await params;
  const pathname = key.join("/");

  const media = await readStoredMedia(pathname);
  if (!media) {
    return NextResponse.json({ ok: false, message: "Not found" }, { status: 404 });
  }

  return new NextResponse(new Uint8Array(media.data), {
    headers: {
      "Content-Type": media.contentType,
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
