
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Deliberately process.env, not prisma/config's `env()` helper — that helper
    // throws immediately if the var is unset, which breaks `prisma generate` (a
    // schema-only operation that needs no live connection) during `npm install`
    // on a freshly-provisioned deploy target before DATABASE_URL has been
    // configured there yet. Anything that actually needs a connection (`prisma
    // migrate`, `db push`, or Prisma Client at runtime) still fails with its own
    // clear "DATABASE_URL not found" error the moment it's used.
    url: process.env.DATABASE_URL ?? "",
  },
});
