import React from "react";
import { Document, Page, View, Text, Image, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import QRCode from "qrcode";
import { formatInTimeZone } from "date-fns-tz";
import { buildQrUrl } from "./token";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Helvetica",
  },
  logo: { width: 90, height: 90, marginBottom: 16, objectFit: "contain" },
  companyName: { fontSize: 22, fontWeight: 700, marginBottom: 4, textAlign: "center" },
  subtitle: { fontSize: 13, color: "#555555", marginBottom: 28, letterSpacing: 1, textAlign: "center" },
  scanLabel: { fontSize: 16, fontWeight: 700, marginBottom: 20, textAlign: "center" },
  qrBox: { padding: 16, borderWidth: 2, borderColor: "#111111", borderRadius: 8, marginBottom: 24 },
  qrImage: { width: 320, height: 320 },
  date: { fontSize: 15, fontWeight: 700, marginBottom: 4, textAlign: "center" },
  office: { fontSize: 13, color: "#333333", marginBottom: 20, textAlign: "center" },
  instructions: { fontSize: 11, color: "#444444", textAlign: "center", lineHeight: 1.5, maxWidth: 360 },
  footer: { position: "absolute", bottom: 24, fontSize: 8, color: "#999999" },
});

interface QrPdfProps {
  companyName: string;
  logoDataUrl?: string | null;
  officeName: string;
  dateLabel: string;
  qrDataUrl: string;
}

function QrPdfDocument({ companyName, logoDataUrl, officeName, dateLabel, qrDataUrl }: QrPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* eslint-disable jsx-a11y/alt-text -- @react-pdf/renderer's Image is a PDF node, not an HTML <img> */}
        {logoDataUrl ? <Image src={logoDataUrl} style={styles.logo} /> : null}
        <Text style={styles.companyName}>{companyName}</Text>
        <Text style={styles.subtitle}>OFFICE ATTENDANCE</Text>
        <Text style={styles.scanLabel}>SCAN TO CLOCK IN</Text>
        <View style={styles.qrBox}>
          <Image src={qrDataUrl} style={styles.qrImage} />
        </View>
        {/* eslint-enable jsx-a11y/alt-text */}
        <Text style={styles.date}>{dateLabel}</Text>
        <Text style={styles.office}>{officeName.toUpperCase()}</Text>
        <Text style={styles.instructions}>
          Scan this QR code to begin attendance. You must also be connected to the
          company&apos;s authorized office network.
        </Text>
        <Text style={styles.footer}>Generated by the {companyName} Attendance System</Text>
      </Page>
    </Document>
  );
}

export interface GenerateQrPdfParams {
  companyName: string;
  logoUrl?: string | null;
  officeName: string;
  attendanceDate: Date;
  timezone: string;
  rawToken: string;
  appUrl: string;
}

async function fetchAsDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const contentType = res.headers.get("content-type") ?? "image/png";
    const buffer = Buffer.from(await res.arrayBuffer());
    return `data:${contentType};base64,${buffer.toString("base64")}`;
  } catch {
    return null;
  }
}

export async function generateQrPdf(params: GenerateQrPdfParams): Promise<Buffer> {
  const qrUrl = buildQrUrl(params.appUrl, params.rawToken);
  const qrDataUrl = await QRCode.toDataURL(qrUrl, { width: 640, margin: 1 });
  const logoDataUrl = params.logoUrl ? await fetchAsDataUrl(params.logoUrl) : null;
  const dateLabel = formatInTimeZone(params.attendanceDate, params.timezone, "EEEE, d MMMM yyyy");

  const doc = (
    <QrPdfDocument
      companyName={params.companyName}
      logoDataUrl={logoDataUrl}
      officeName={params.officeName}
      dateLabel={dateLabel}
      qrDataUrl={qrDataUrl}
    />
  );

  return renderToBuffer(doc);
}

export async function generateQrPngDataUrl(rawToken: string, appUrl: string): Promise<string> {
  const qrUrl = buildQrUrl(appUrl, rawToken);
  return QRCode.toDataURL(qrUrl, { width: 640, margin: 1 });
}
