import { prisma } from "@/lib/db/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { generateQrAction, deactivateQrAction } from "@/lib/actions/qr";
import { getAttendanceSettings } from "@/lib/attendance/settings";
import { formatInTimeZone } from "date-fns-tz";
import { PageHeader } from "@/components/admin/PageHeader";

export const dynamic = "force-dynamic";

const STATUS_STYLES: Record<string, string> = {
  ACTIVE: "bg-green-100 text-green-700",
  SCHEDULED: "bg-blue-100 text-blue-700",
  EXPIRED: "bg-gray-200 text-gray-700",
  DEACTIVATED: "bg-red-100 text-red-700",
};

export default async function QrPage() {
  const [offices, qrCodes, settings] = await Promise.all([
    prisma.office.findMany({ orderBy: { name: "asc" } }),
    prisma.attendanceQrCode.findMany({
      include: { office: true, generatedBy: true },
      orderBy: { createdAt: "desc" },
      take: 30,
    }),
    getAttendanceSettings(),
  ]);

  const todayStr = formatInTimeZone(new Date(), settings.timezone, "yyyy-MM-dd");

  return (
    <>
      <PageHeader>
        <h1 className="text-2xl font-bold">QR Codes</h1>
        <p className="text-sm text-muted-foreground">
          Attendance mode is <strong>{settings.attendanceMode.replace(/_/g, " ")}</strong>.{" "}
          {settings.attendanceMode === "QR_ONLY" ? (
            <span className="text-amber-700">
              QR_ONLY provides weaker physical-presence verification than QR_AND_NETWORK.
            </span>
          ) : null}
        </p>
      </PageHeader>
      <div className="space-y-6 px-4 py-6 sm:px-6 md:px-8">
      <Card>
        <CardHeader>
          <CardTitle>Generate QR</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={generateQrAction} className="flex flex-wrap items-end gap-2">
            <div>
              <label className="mb-1 block text-xs font-medium text-muted-foreground">Office</label>
              <select name="officeId" required className="h-9 rounded-md border border-input bg-background px-2 text-sm">
                {offices.map((o) => (
                  <option key={o.id} value={o.id}>
                    {o.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="mb-1 block text-xs font-medium text-muted-foreground">Date</label>
              <Input type="date" name="date" defaultValue={todayStr} className="h-9 w-40" />
            </div>
            <Button type="submit" size="sm">
              Generate / Regenerate
            </Button>
          </form>
          {offices.length === 0 ? (
            <p className="mt-2 text-sm text-amber-700">Create an office first.</p>
          ) : null}
        </CardContent>
      </Card>

      <div className="overflow-x-auto rounded-lg border bg-card">
        <table className="w-full text-sm">
          <thead className="border-b bg-muted/50 text-left text-xs uppercase text-muted-foreground">
            <tr>
              <th className="px-4 py-2">Office</th>
              <th className="px-4 py-2">Date</th>
              <th className="px-4 py-2">Status</th>
              <th className="px-4 py-2">Generated By</th>
              <th className="px-4 py-2" />
            </tr>
          </thead>
          <tbody>
            {qrCodes.map((qr) => (
              <tr key={qr.id} className="border-b last:border-0">
                <td className="px-4 py-2">{qr.office.name}</td>
                <td className="px-4 py-2">{qr.attendanceDate.toISOString().slice(0, 10)}</td>
                <td className="px-4 py-2">
                  <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_STYLES[qr.status]}`}>
                    {qr.status}
                  </span>
                </td>
                <td className="px-4 py-2">{qr.generatedBy.fullName}</td>
                <td className="px-4 py-2">
                  <div className="flex justify-end gap-3">
                    {qr.pngUrl ? (
                      <a href={qr.pngUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline">
                        PNG
                      </a>
                    ) : null}
                    {qr.pdfUrl ? (
                      <a href={qr.pdfUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline">
                        PDF
                      </a>
                    ) : null}
                    {qr.status === "ACTIVE" || qr.status === "SCHEDULED" ? (
                      <form action={deactivateQrAction.bind(null, qr.id)}>
                        <button type="submit" className="text-red-600 hover:underline">
                          Deactivate
                        </button>
                      </form>
                    ) : null}
                  </div>
                </td>
              </tr>
            ))}
            {qrCodes.length === 0 ? (
              <tr>
                <td colSpan={5} className="px-4 py-8 text-center text-muted-foreground">
                  No QR codes generated yet.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
      </div>
    </>
  );
}
